name: "gojob"

services:
  mysql57:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 23306:3306
    # Use root/example as user/password credentials
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
      TZ: Asia/Shanghai
    volumes:
      - mysql57_data:/var/lib/mysql

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "26379:6379"
    volumes:
      - $PWD/data:/data:rw
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

volumes:
  mysql57_data:
